2023-12-25 16:59:15,728 INFO shopapp.views: Rendering shop index
2023-12-25 16:59:16,090 INFO shopapp.views: Rendering shop index
2023-12-25 16:59:16,522 INFO shopapp.views: Rendering shop index
2023-12-25 17:02:16,225 INFO django.utils.autoreload: /home/vysnik/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2023-12-25 17:02:16,652 INFO django.utils.autoreload: Watching for file changes with StatReloader
2023-12-27 16:39:18,688 INFO django.utils.autoreload: Watching for file changes with StatReloader
2023-12-27 16:39:30,204 WARNING django.request: Not Found: /
2023-12-27 16:39:40,342 WARNING django.request: Not Found: /__debug__/
2023-12-27 16:39:42,594 WARNING django.request: Not Found: /__debug__/
2023-12-27 16:39:45,414 WARNING django.request: Not Found: /__debug__
2023-12-30 17:39:16,154 INFO django.utils.autoreload: Watching for file changes with StatReloader
2023-12-30 17:39:35,987 WARNING django.request: Not Found: /
2023-12-30 17:39:35,992 WARNING django.request: Not Found: /
2023-12-30 17:39:37,684 WARNING django.request: Not Found: /favicon.ico
2023-12-30 17:39:38,397 WARNING django.request: Not Found: /
2023-12-30 17:39:49,237 INFO shopapp.views: Rendering shop index
2023-12-30 17:39:49,484 WARNING django.request: Not Found: /favicon.ico
2023-12-31 09:24:13,822 INFO django.utils.autoreload: Watching for file changes with StatReloader
2023-12-31 09:24:27,792 WARNING django.request: Not Found: /
2023-12-31 09:24:34,579 INFO shopapp.views: Rendering shop index
2024-01-01 12:12:44,947 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-01 12:12:59,797 WARNING django.request: Not Found: /
2024-01-01 12:16:31,627 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-01 12:16:34,893 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-01 12:17:18,127 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-01 12:17:18,924 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-01 12:17:20,170 ERROR django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 238, in get
    name = elem["nae"]
KeyError: 'nae'
2024-01-01 12:31:58,158 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2024-01-01 12:31:59,316 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-01 12:32:11,273 ERROR django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 238, in get
    name = elem["nae"]
KeyError: 'nae'
2024-01-01 12:34:13,819 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-01 12:34:14,392 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 16:36:21,049 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 16:36:36,214 WARNING django.request: Not Found: /
2024-01-04 16:37:12,211 WARNING django.request: Not Found: /favicon.ico
2024-01-04 16:37:29,120 WARNING django.request: Not Found: /favicon.ico
2024-01-04 16:46:05,519 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-04 16:46:08,767 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 16:46:11,117 ERROR django.request: Internal Server Error: /en/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_modify.py", line 65, in submit_row
    add = context["add"]
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'add'
2024-01-04 16:46:42,123 WARNING django.request: Not Found: /favicon.ico
2024-01-04 17:06:37,082 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-04 17:06:41,621 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 17:06:43,520 WARNING django.request: Not Found: /favicon.ico
2024-01-04 17:07:13,459 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-04 17:07:14,455 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 17:09:04,364 ERROR django.request: Internal Server Error: /en/admin/shopapp/product/import_products_csv/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: shopapp_product.created_by_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/admin.py", line 95, in import_csv
    Product.objects.bulk_create(products)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 803, in bulk_create
    returned_columns = self._batched_insert(
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1831, in _batched_insert
    self._insert(
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 641, in execute
    result = real_execute(self, sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: shopapp_product.created_by_id
2024-01-04 17:16:09,731 WARNING django.request: Not Found: /en/products
2024-01-04 17:16:15,481 INFO shopapp.views: Rendering shop index
2024-01-05 08:49:36,897 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-05 08:49:52,885 WARNING django.request: Not Found: /
2024-01-05 09:16:37,807 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-05 09:16:40,211 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-05 09:16:45,308 WARNING django.request: Not Found: /favicon.ico
2024-01-05 09:16:55,866 WARNING django.request: Method Not Allowed: /ru/shop/api/products/upload_csv/
2024-01-07 09:37:50,159 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-07 09:38:23,092 WARNING django.request: Not Found: /
2024-01-07 09:38:24,410 WARNING django.request: Not Found: /
2024-01-08 07:52:04,939 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 07:52:18,071 WARNING django.request: Not Found: /
2024-01-08 07:53:12,412 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2024-01-08 07:53:13,447 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 07:57:17,124 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/urls.py changed, reloading.
2024-01-08 07:57:18,986 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 07:57:19,408 WARNING django.request: Not Found: /blog/
2024-01-08 07:57:32,569 WARNING django.request: Not Found: /blog/articles/1/
2024-01-08 08:02:35,739 WARNING django.request: Not Found: /blog/articles/1/
2024-01-08 08:11:55,822 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2024-01-08 08:11:56,670 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 08:12:17,337 ERROR django.request: Internal Server Error: /blog/articles/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'article' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['blog/articles/(?P<pk>[0-9]+)/\\Z']
2024-01-08 08:12:18,863 ERROR django.request: Internal Server Error: /blog/articles/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'article' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['blog/articles/(?P<pk>[0-9]+)/\\Z']
2024-01-08 08:14:15,483 ERROR django.request: Internal Server Error: /blog/articles/3/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blogapp/article_detail.html
2024-01-08 08:23:35,078 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/admin.py changed, reloading.
2024-01-08 08:23:36,166 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 08:24:19,059 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/admin.py changed, reloading.
2024-01-08 08:24:19,631 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 08:59:01,212 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2024-01-08 08:59:02,734 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 09:11:13,386 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 16:13:56,980 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 16:14:15,917 WARNING django.request: Not Found: /
2024-01-08 16:14:32,799 ERROR django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sitemap.xml
2024-01-08 16:16:15,013 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2024-01-08 16:16:16,968 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-09 16:54:09,805 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-09 16:54:28,357 WARNING django.request: Not Found: /
2024-01-11 15:08:33,325 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-11 15:08:47,748 WARNING django.request: Not Found: /
2024-01-11 15:15:10,922 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-11 15:15:14,472 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-11 15:17:52,030 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-11 15:17:53,348 INFO django.utils.autoreload: Watching for file changes with StatReloader
